### ISSUE TITLE
Ability to cancel and retry authorization or registration

### ISSUE THREAD

**Issue by udaychandra** [corbado/flutter-passkeys#37]
Hello,

I've encountered situations with iOS where an error gets thrown when authenticateWithAutoComplete is triggered:
`ASAuthorizationController credential request failed with error: Error Domain=com.apple.AuthenticationServices.AuthorizationError Code=1004 "(null)"`

And when a subsequent call to authenticateWithEmail is triggered, this error gets thrown:
`flutter: PlatformException(failed, The operation couldn’t be completed. Request already in progress for specified application identifier., , null)`

It would be extremely helpful if PasskeyAuth can auto-cancel via something like ASAuthorizationController or if a cancel method is provided on the interface that can be programmatically invoked.

### Environment Details
Flutter 3.16.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db7ef5bf9f (2 weeks ago) • 2023-11-15 11:25:44 -0800
Engine • revision 74d16627b9
Tools • Dart 3.2.0 • DevTools 2.28.2

Real iPhone, iOS version 17.1.1

My flutter app is fully configured to support passkeys. Associated domains fully configured. Our domain's apple-app-site-association can be reached by Apple's CDN (https://app-site-association.cdn-apple.com/a/v1/our-domain

And thank you providing this excellent package to the community!

**Comment by vincentdelitz** [comment]
Thanks for opening the issue, we'll look into it!

**Comment by incorbador** [comment]
Hi, thanks for the suggestion, sounds like a valid point. 
Can you please give me a short description on how to reproduce the error ("Request already in progress for specified application identifier")?

**Comment by vincentdelitz** [comment]
@udaychandra does the issues still exist? Otherwise, I would close this issue.

**Comment by udaychandra** [comment]
Thanks for checking. Hard to reproduce. Closing it.
