### ISSUE TITLE
Why the login to google is required ?

### ISSUE THREAD

**Issue by DouOlin** [corbado/flutter-passkeys#40]
Hey, cannot implement this package without be logged in into google account?

**Comment by vincentdelitz** [comment]
Hi @DouOlin,

Thanks for your question.
I assume you're referencing to the Android implementation of the passkeys package. The reason why you need to be logged into a Google account lies in the nature of Google's dealing with passkeys on Android. Passkeys are synced credentials and this synchronization happens via Google Password Manager (so ultimately via your Google account). Google just enforces every credential / passkey to be synced on Android, so need to be logged-in to use passkeys.

I hope that answers your question - let me know if you have more questions.

Best,
Vincent
