### ISSUE TITLE
missing `icon` in extension.yaml

### ISSUE THREAD

**Issue by pr-Mais** [corbado/flutter-passkeys#42]
Hey, through the review process for your extension, I noticed you're missing an icon, that is important for showing it in the marketplace. You can add one and send it for review again.

Find the docs on how to add it [here](https://firebase.google.com/docs/extensions/reference/extension-yaml).

**Comment by incorbador** [comment]
Thanks a lot for the hint 👍 We just added it and submitted a new version for review :)

**Comment by incorbador** [comment]
New version including the icon got accepted.
