### ISSUE TITLE
Update from 1.3.2 to 2.0.4 issue

### ISSUE THREAD

**Issue by ynlvko** [corbado/flutter-passkeys#51]
Greetings! I'm currently using `passkeys 1.3.2` in my project. However, when updating to the latest version 2.0.4, I encountered a backward compatibility issue on iOS, whereas Android functions as expected.

With passkeys registered under version 1.3.2, logging in using version 2.0.4 is not possible. Upon investigation, I discovered the following discrepancy:
- Version 1.3.2 sends `userHandle: NTkxMTE4`, equivalent to `591118` in base64.
- Version 2.0.4 sends `userHandle: TlRreE1URTQ`, which translates to `NTkxMTE4` in base64, indicating that `userHandle` undergoes double encoding.

Is there a way to maintain the previous behavior to ensure the compatibility of passkeys saved by users?

**Comment by vincentdelitz** [comment]
hey @ynlvko,
Thanks for bringing this up - we'll take a look into it.

**Comment by incorbador** [comment]
Hey @ynlvko. You have a valid question. 

The background of this change was that other libraries like webauthn-json treat userHandle as base64. So if this package would create credentials with a userHandle that is not base64 encoded, the credential could not be used by an application that uses webauthn-json. 
We use webauthn-json as a dependency for the flutter web plugin of the passkeys package.

By encoding userHandle in base64 you can now use the passkeys package in a native app to create a credential that can then be used in the web version of that same app (even on a different device). 

Unfortunately, there is no easy solution to this problem (I think). The only way to handle it that comes to my mind is that you catch that in your relying party server backend. You could have logic there that checks for the double encoding (by checking if you can base64 decode the handle for a second time) or you take the timestamp when the passkey was created into account.

**Comment by ynlvko** [comment]
Thanks for the response! It makes sense now.
