### ISSUE TITLE
Unable to build iOS after plugin update from 1.1.0 to 2.0.7

### ISSUE THREAD

**Issue by Talal0** [corbado/flutter-passkeys#56]
I've updated passkeys plugin from 1.1.0 to 2.0.7 I'm getting error while building for iOS 
Swift Compiler Error (Xcode): Value of type 'ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest' has no member 'excludedCredentials' 
.pub-cache/hosted/pub.dev/passkeys_ios-2.0.3/ios/Classes/PasskeysPlugin.swift:56:20

**Comment by incorbador** [comment]
Hey, @Talal0. I just build this repository's example for the passkey package twice (once for iOS 16.4 and once for iOS 17.0 and both builds were working fine). 

Can you do me a favour and take a look into this file please?
.pub-cache/hosted/pub.dev/passkeys_ios-2.0.3/ios/Classes/PasskeysPlugin.swift:56:20

At line 56 it should look like this (this is the code that we published with version 2.0.3), but judging from the error message you provided, this seems not to be the case.
<img width="852" alt="image" src="https://github.com/corbado/flutter-passkeys/assets/134682658/086c7490-c43b-4a46-a7b7-6e41ede953c7">

**Comment by Talal0** [comment]
Hello @incorbador thanks for your response, The code you mentioned is present in the class but its declaration was missing so I updated Xcode version to 15.3 (15E204a) resolved my issue.

**Comment by incorbador** [comment]
Hey @Talal0. Thanks for the response => good to know (I am pretty sure that other devs will need this as well) 👍
