### ISSUE TITLE
Intl 0.19 required by latest Flutter version.

### ISSUE THREAD

**Issue by cekrozl1** [corbado/flutter-passkeys#65]
Hello Corbado team,

When adding the passkeys 2.0.8 in pubspec.yaml, I see this error :  

> Because passkeys >=1.2.0 depends on corbado_frontend_api_client ^1.1.0 which depends on intl ^0.18.0, passkeys >=1.2.0 requires intl ^0.18.0.
> And because every version of flutter_localizations from sdk depends on intl 0.19.0, passkeys >=1.2.0 is incompatible with flutter_localizations from sdk.
> So, because third_generation depends on both flutter_localizations from sdk and passkeys ^2.0.8, version solving failed.

My flutter doctor looks like this:

> ❯ flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale en-BE)
> [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 15.4)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2023.3)
> [✓] VS Code (version 1.90.0)
> [✓] Connected device (5 available)
> [✓] Network resources

Would it be possible to update intl in corbado_frontent_api_client ?

Thank you !

**Comment by incorbador** [comment]
Hey @cekrozl1, we published a new version for corbado_api_client (1.1.1). The issue should now be fixed (you just need to run `flutter pub get` again).

**Comment by incorbador** [comment]
@ice-orion yes, we just published a new version of the passkeys package (v2.0.9) that includes this change. Sorry for the delay. 

Would be great if you can confirm that this fixes the issue for you :)

**Comment by PeterStaev** [comment]
v2.0.9 fixed the intl issue for me!

**Comment by incorbador** [comment]
Cool, thanks for reporting this and for helping us to test the fix 👍 
Will close the ticket for now :)
