### ISSUE TITLE
Cannot get web version to run

### ISSUE THREAD

**Issue by Fohlen** [corbado/flutter-passkeys#66]
Dear Corbado-Team, I have been trying to get the web version of flutter-passkeys up and running.

This is mostly for convenience because I like debugging in my browser instead of adding 16GB of RAM for an emulator.

Steps I have done:

1. Create a new flutter app
2. Install `corbado_auth` 
3. Copy the [auth_service](https://github.com/corbado/flutter-passkeys/blob/main/packages/corbado_auth/example/lib/auth_service.dart)
4. Start the service via `flutter run --define-dart=CORBADO_PROJECT_ID=myid lib/main.dart` 

When I run this part, it boots up with the following error message:

```
Rejecting promise with error: TypeError: Cannot read properties of undefined (reading 'init')

A message on the flutter/lifecycle channel was discarded before it could be handled.
This happens when a plugin sends messages to the framework side before the framework has had an opportunity to register a listener. See the ChannelBuffers API documentation for details on how to configure the channel to expect more messages, or to expect messages to get discarded:
  https://api.flutter.dev/flutter/dart-ui/ChannelBuffers-class.html
A message on the flutter/lifecycle channel was discarded before it could be handled.
This happens when a plugin sends messages to the framework side before the framework has had an opportunity to register a listener. See the ChannelBuffers API documentation for details on how to configure the channel to expect more messages, or to expect messages to get discarded:
  https://api.flutter.dev/flutter/dart-ui/ChannelBuffers-class.html
Application finished.
```

My versions:

- Flutter 3.22.2
- Dart 3.4.3
- corbado_auth: ^2.0.7

I am trying to run this on a MacOS device (14.5).
Did I miss anything about the setup or is this simply a bug?

**Comment by Fohlen** [comment]
Well, I found the reason this wasn't able to run. The corbado_auth web version example ships with a `bundle.js` containing an implementation for the `PasskeyAuthenticator`. This is documented nowhere. Funnily enough it is also licensed to Microsoft. Including this `bundle.js` gets the example off the ground. Definitely needs documentation refinement.

**Comment by incorbador** [comment]
You correctly identified your issue. When you make use of the web version of passkeys web you have to include a bundled version of a JS library of us. 

While I fully agree that this is not explained well it's a bit unfair to claim that this is not documented anywhere. If you read through the README of passkeys library on pub.dev you can see that we mention this. 

<img width="862" alt="image" src="https://github.com/user-attachments/assets/53ecde2b-3f7a-44ef-b2d8-8cda68643503">


Feel free to submit a PR to make this more clear though :)

**Comment by incorbador** [comment]
@Fohlen What do you mean by "Funnily enough it is also licensed to Microsoft"?

**Comment by Fohlen** [comment]
Hi, sorry, I did not see the documentation on the passkeys package, I expected it to be in `corbado_auth`. The demo example from which I copied licenses the bundle to Microsoft, [see here](https://github.com/corbado/flutter-passkeys/blob/main/packages/passkeys/passkeys/example/web/bundle.js#L5)
