### ISSUE TITLE
Dependency error with corbado_frontend_api_client

### ISSUE THREAD

**Issue by phuchuynhStrong** [corbado/flutter-passkeys#70]
I added `passkeys: 2.0.8` and can't resolve dependency. The error is
`Resolving dependencies... (1.4s)
Because corbado_frontend_api_client >=1.1.1 depends on openapi_generator_annotations ^5.0.2 and passkeys >=0.1.0 depends on openapi_generator_annotations ^4.10.0, corbado_frontend_api_client >=1.1.1 is incompatible with passkeys >=0.1.0.
So, because modules depends on both passkeys 2.0.8 and corbado_frontend_api_client ^1.1.1, version solving failed.`
I check the cache directory from `.pub-cache/hosted/pub.dev/passkeys-2.0.8` and it is not the latest code from Git which removed the `openapi_generator_annotations`. I think we should bump up a new version to get this resolved. Thanks

**Comment by incorbador** [comment]
Correct, thanks for the hint. We just published a new version of the passkeys package that fixes this issue. I have tested it in the example application of the passkeys package. 

Can you verify as well that the issue is solved from your project please?

**Comment by phuchuynhStrong** [comment]
Thanks you. The issue is resolved
