### ISSUE TITLE
Failed to parse response when trying to do cross device authentication.

### ISSUE THREAD

**Issue by rvn9** [corbado/flutter-passkeys#72]
So the current `passkeyAuthenticator.authenticate` function is returning AuthenticateResponseType, but when i try to authenticate using passkey on another device (private key on device A that used to login on device B). the response type is below, which is different from AuthenticateResponseType.

`{
  "rawId": "VnyekU7Pp3C4B8oTY0Hx-A",
  "authenticatorAttachment": "cross-platform",
  "type": "public-key",
  "id": "VnyekU7Pp3C4B8oTY0Hx-A",
  "response": {
    "clientDataJSON": "eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoid3BrcUtLb09NaG1pN2NvVFZva056YVBEeWdwM2pJdk8xLTIzSWxibS1nUSIsIm9yaWdpbiI6ImFuZHJvaWQ6YXBrLWtleS1oYXNoOkxOYmlZYmxCTm5HQ3k2a1lXOTlnOFpEdDB6Z1YyRW04aWdVWUJkNzdRckUiLCJhbmRyb2lkUGFja2FnZU5hbWUiOiJjb20uZXhhbXBsZS5mbHV0dGVyX3Bhc3NrZXlfdGVzdCJ9",
    "authenticatorData": "vFRfReoKqgs6BsspvBYtr6Mc2SNzjOzZO4I25cZifSQdAAAAAA",
    "signature": "MEYCIQDCFUCSNygYZ8VMMgOvkujFhajSpIqpMSPnL4oHp1hXiwIhAJbZX-3xtZAMmwSzkOlIRVGzsI4cLQIc_tpm-z0qOiPF"
  },
  "clientExtensionResults": {}
}`

which caused org.json.JSONException: No value for userHandle (parsing error).

**Comment by wordlesser** [comment]
How was the problem solved?
